### ISSUE TITLE
Where's all the tags?

### ISSUE THREAD

**Issue by spyhunter99** [hyperic/sigar#102]
There's a number of versions published to maven central with version numbers like
1.6.5.132-6
as seen here

https://mvnrepository.com/artifact/org.hyperic/sigar-dist
https://mvnrepository.com/artifact/org.hyperic/sigar

however there are no tags in this git repo. Anyone have an idea where redhat keeps their code for this repo?

**Comment by AlexYaruki** [comment]
As only available in RedHat maven repository, they can have internal git for it. It is not definitely here. Sigar is used on one of their monitoring solutions.

**Comment by spyhunter99** [comment]
@AlexYaruki do you know if there is any active development over there or what the deltas are?

**Comment by AlexYaruki** [comment]
In their repository (https://maven.repository.redhat.com/ga/org/) hyperic package was last modified "Tue Oct 11 20:26:48 EDT 2016"

**Comment by AlexYaruki** [comment]
Just confirmed, they are using new version 1.6.5.132-6 in RHQ: https://github.com/rhq-project/rhq/blob/82fbacbc7f3944e09809abad13ad9d44a42afae7/pom.xml

**Comment by spyhunter99** [comment]
ha and i thought my pom was large!

so that project is using it, but it looks like unfortunately the sources for that artifact is not available. Bad news for me, cause that's what I'm using and the APIs are not align with this repo. Specifically, there's a few of additional classes added and i happen to be using, `org.hyperic.sigar.NetConfigInterface` and can't find javadocs anywhere.

**Comment by AlexYaruki** [comment]
Javadocs were available on documentation site ( https://support.hyperic.com/display/SIGAR/Home ) but is down for maintenance.

**Comment by spyhunter99** [comment]
Yeah but that's probably for *this repo's source, the redhat fork is
different and since it's the only thing published as a maven artifact

**Comment by AlexYaruki** [comment]
Yes, this was for "this" repo. I found information about RedHat version just recently so don't no anything about besides RedHat maven repo.

**Comment by spyhunter99** [comment]
quick update, the redhat/jboss artifacts published to jboss's maven repo have javadocs bundled with it. Unfortunately, most the javadocs are missing important content like... units. I.e. what unit of measure do the functions return, seconds, ms, ns, etc
