### ISSUE TITLE
aarch64 build of sigar, for Alpine Linux

### ISSUE THREAD

**Issue by vielmetti** [hyperic/sigar#104]
Alpine Linux has an open feature request https://bugs.alpinelinux.org/issues/7011 to add sigar to Alpine for aarch64 (ARMv8, arm64, 64-bit ARM). This issue is to track any sigar details relative to that platform for that port.

The request notes that "This package is a dependency for the official Crate.io (DB) Docker image (based off alpine:3.5)."

**Comment by ncopa** [comment]
build fails with:

````
jni-compile:

jni-cc:
    [mkdir] Created dir: /home/ncopa/aports/community/sigar/src/sigar-sigar-1.6.4/bindings/java/build/obj/aarch64-linux/lib
     [echo] jni libname=sigar-aarch64-linux
       [cc] 13 total files to be compiled.
       [cc] gcc: error: unrecognized command line option '-m64'

BUILD FAILED
/home/ncopa/aports/community/sigar/src/sigar-sigar-1.6.4/bindings/java/hyperic_jni/jni-build.xml:224: The following error occurred while executing this line:
/home/ncopa/aports/community/sigar/src/sigar-sigar-1.6.4/bindings/java/hyperic_jni/jni-build.xml:270: gcc failed with return code 1

Total time: 5 seconds
````

**Comment by vielmetti** [comment]
I'm suspicious of the code at 

https://github.com/hyperic/sigar/blob/master/bindings/java/hyperic_jni/src/org/hyperic/jni/ArchNameTask.java#L75

which sets the `-m64` compiler flag.

**Comment by vielmetti** [comment]
There is a patch at https://git.alpinelinux.org/aports/commit/?h=v3.10.0&id=e47b327a5cca7fc6a3ed1b67ebac4fa652b51042 which adds this support for aarch64.
