### ISSUE TITLE
sigar_boot_time_get always return SIGAR_OK for LINUX

### ISSUE THREAD

**Issue by cngzhnp** [hyperic/sigar#121]
After file can be read succesfully, **btime** is checked in buffer string.  If **btime** cannot be found or something goes wrong when reading then **found** variable was not changed and remained zero as before.

So, even boot time cannot be found function returns SIGAR_OK, however, it is not expected. There is no information provided to user, boot time shows that current time. 

My suggestion is, return value should be different OK, to pass valuable info to user something goes wrong.

For instance:

```
if (!found) {
   /* should never happen */
   sigar->boot_time = time(NULL);
   return SIGAR_BOOT_TIME_ERROR;
}
return SIGAR_OK;
```

**Comment by kostya** [comment]
btw in my fork, i change this function: https://github.com/kostya/sigar/commit/660259
i find this more correct, and this is also how it implements in gnu ps. 
the problem was when time auto corrected after restart, btime can contain wrong value, and this affect on start_time function.

**Comment by cngzhnp** [comment]
Thanks @kostya, much better now. IMHO if function returns **int** type, it should give more information about what was done in function body. If it returns always OK, I was not sure that btime was correct or not.
