### ISSUE TITLE
http://sigar.hyperic.com/ doesn't respond

### ISSUE THREAD

**Issue by msgoff** [hyperic/sigar#137]

**Comment by dbwiddis** [comment]
Hyperic was acquired by SpringSource, later acquired by VMWare.  The date of the acquisition correlates rather well with termination of SIGAR releases and abandonment of the project.  As the Hyperic products have now been superseded by other VMWare offerings, they have no motivation to continue supporting it.

You can [find some old docs on The Wayback Machine](https://web.archive.org/web/20070821124703/http://www.hyperic.com/support/docs/sigar/).

**Comment by msgoff** [comment]
Thank you for responding!
