### ISSUE TITLE
Support Solaris version 11

### ISSUE THREAD

**Issue by goranceko** [hyperic/sigar#139]
Get correct values for: 
CPU, memory, filesystems, openfiles

Arch:
* sparc-32
* sparc-64
* x86
* x64

**Comment by dbwiddis** [comment]
Nobody is developing SIGAR anymore.  You might wish to search for [other alternatives](https://github.com/oshi/oshi) which provide the functionality you request.

**Comment by Sidabw** [comment]
thanks
