### ISSUE TITLE
Can't install in Yosemite

### ISSUE THREAD

**Issue by miharekar** [hyperic/sigar#47]
This are the errors I get: https://gist.github.com/mrfoto/4dc512a19a23bc03e962

I found via Googling that @drnic had a very similar error, but doesn't describe how he fixed it https://gist.github.com/drnic/4210300

All other gems are installing normally, I have latest gcc

```
gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

**Comment by tmeinlschmidt** [comment]
Hey @alexwoll, can you please try to clone my fork, build a gem via `rake gem` and install from `pkg` directory?

**Comment by kasrinat** [comment]
There is a recommendation that GeStalt should not be used on Yosemite. NSProcessInfo is recommended instead for OS name, version etc.
Are you going to accept patches to darwin_sigar.c with this change?
Thanks
