### ISSUE TITLE
Java bindings, trouble loading native library

### ISSUE THREAD

**Issue by spyhunter99** [hyperic/sigar#98]
I'm running into a strange issue where by sigar isn't locating or loading the native library. Not entirely sure why but I figured I'd throw this out there to see if anyone has any options i can troubleshoot with.

````
SigarLoader loader = new SigarLoader(Sigar.class);
System.out.println(loader.getLibraryName());
````

The output is `libsigar-amd64-linux.so'. This file is present and available on the class path so I'm not entirely sure what the issue is. The file is readable by the current user.

Shortly aftewards, it i get an UnsatifiedLinkError when loading OperatingSystem.getInstance @ SysInfo.gather(Native method)

Any help is appreciated

**Comment by AlexYaruki** [comment]
How did you included Sigar ? If, by Maven, which dependency ?

**Comment by spyhunter99** [comment]
@AlexYaruki basically, i'm including the sigar-dist-bin artifact, then unzipping and copying the .dll/so files into the working directory of the java process. The pom is here

https://github.com/mil-oss/fgsms/blob/master/fgsms-agents/fgsms.OSAgent/pom.xml

If it helps, this is on a custom flavor of Linux so it's possible that the precompiled .so is somehow incompatible with the os/kernel version. In that case, I would expect a slightly different error message than UnsatifiedLinkError, but i have little experience with JNI problems. I'll try recompiling native lib and go from there.

**Comment by AlexYaruki** [comment]
Do you change java.library.path when running the application ? Libraries for jni are searched in directories in this property.

**Comment by AlexYaruki** [comment]
Also, try debugging information from dynamic linker (LD_DEBUG, http://man7.org/linux/man-pages/man8/ld.so.8.html) Hope this helps

**Comment by spyhunter99** [comment]
@AlexYaruki ha the good old java -Djava.library.path=. myjar.jar fixed it. Should have tried it sooner. Thanks for the pointer!
